config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :teachers
  devise_for :users

  root 'frontend#index'

  namespace :admin do
    get '/' => 'dashboard#index'
    get '/tesztemail' => 'dashboard#tesztemail'
    get '/incrementdate' => 'dashboard#incrementdate'
    get '/pdf' => 'dashboard#pdf'
    resources :courses do
        resources :lessons
    end
    resources :users
    get 'diakok' => 'users#index'
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
    has_many :lessons
    has_attached_file :logo, 
        styles: {
            thumb: "100x100>" 
        }, 
        default_url: "/logo/:style/missing.png",
        url: "/logo/:hash.:extension",
        hash_secret: "longSecretString"

    validates :name, presence: true
    validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/credit.rb
class Credit < ActiveRecord::Base
    belongs_to :user
    belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
    has_many :presences
    has_many :users, through: :presences
    has_many :credits
    belongs_to :course

    validates :datum, :allapot, presence: true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    belongs_to :user

    validates :type, inclusion: { in: %w(banktransfer creditcard) }
    with_options if: :paid_with_card? do |cc|
      validates :cardprovider, presence: true
      validates :cardprovider, inclusion: { in: %w(visa mastercard maestro) }
    end

private
    def paid_with_card?
      self.type == 'creditcard'
    end
end

app/models/presence.rb
class Presence < ActiveRecord::Base
    belongs_to :user
    belongs_to :lesson

    validates :user_id, :lesson_id, presence: true

    after_save do |presence|
        c = Credit.new
        c.user_id = self.user_id
        c.lesson_id = self.lesson_id
        c.date = Date.parse(Time.now.to_s).to_s
        c.credit = self.lesson.creditvalue
        c.save
    end
    
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user.rb
class DateValidator < ActiveModel::Validator
    def validate(record)
        record.errors[:birthdate] << "not valid" if Date.parse(record.birthdate.to_s).year < 1900
    end
end

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :presences, dependent: :destroy
    has_many :lessons, through: :presences
    has_many :payments, dependent: :destroy
    has_many :credits, dependent: :destroy

    validates :firstname, :lastname, :birthdate, presence: true
    validates :birthdate, format: { with: /\A[0-9]{4}.[0-9]{2}.[0-9]{2}.?\z/ }
    validates_with DateValidator

    def name
      self.firstname + " " + self.lastname
    end

    def lessoncount
        self.lessons.count
    end

    def credit
        credit = 0
        self.credits.each do |c|
            credit += c.credit
        end
        return credit
    end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
    before_action :authenticate_teacher!, except: [:index]

    def tesztemail
        Mailer.tesztemail.deliver_later(wait: 10)
        redirect_to admin_path
    end

    def incrementdate
        BackendJob.set(wait: 30).perform_later
    end

    def pdf
        pdf = Prawn::Document.new
        pdf.stroke_axis
        Course.all.each do |c|
        pdf.text c.name
        pdf.move_down 10
        end
        headers["Content-Type"] = "application/pdf"
        send_data pdf.render
    end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController
    def edit
        @course = Course.find(params[:id])
    end

    def update
        course = Course.find(params[:id])
        course.update!(course_params)
        redirect_to admin_path
    end

    def new
        @course = Course.new
    end

    def create
        @course = Course.new(course_params)
        if @course.save
            redirect_to admin_path
        else
            flash[:error] = 'abc'
            render :new
        end
    end

    def destroy
        Course.find(params[:id]).destroy
        redirect_to admin_path
    end
private
    def course_params
        params.require(:course).permit(:datum, :name, :logo)
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController
    def index
        @courses = Course.all
    end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::AdminController

    def index
        @course = Course.find(params[:course_id])
        @lessons = @course.lessons
    end

    def new
        @lesson = Course.find(params[:course_id]).lessons.new
    end

    def create
        @lesson = Course.find(params[:course_id]).lessons.new(lesson_params)
        if @lesson.save
            redirect_to admin_course_lessons_path
        else
            render :new
        end
    end

    def edit
        @lesson = Lesson.find(params[:id])
    end

    def update
        lesson = Lesson.find(params[:id])
        if lesson.update!(lesson_params)
          flash[:notice] = "##{params[:id]} record successfully updated!"
        else
          flash[:notice] = "Ohh ooooohh, something wrong happend!"
        end
        redirect_to admin_course_lessons_path(params[:course_id])
    end
private
    def lesson_params
        params.require(:lesson).permit(:datum, :allapot)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

    def index
        @users = User.all
    end

    def new
        @user = User.new
        @courses = Course.all
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to admin_users_path
        else
            render :new
        end

        presence_save(params)
    end

    def edit
        @user = User.find(params[:id])
        @courses = Course.all
    end

    def update
        @user = User.find(params[:id])
        if @user.update!(user_params)
          flash[:notice] = "##{params[:id]} record successfully updated!"
        else
          flash[:notice] = "Ohh ooooohh, something wrong happend!"
        end

        presence_save(params)

        redirect_to admin_users_path
    end

    def destroy
        User.find(params[:id]).destroy

        redirect_to admin_users_path
    end
private
    def user_params
        params.require(:user).permit(:firstname, :lastname, :birthdate)
    end

    def presence_save(params)
        @user.lessons.destroy_all
        return unless params[:lesson].is_a?(Hash)
        params[:lesson].each do |k,v|
            @user.lessons << Lesson.find(k)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
    def index
        @courses = Course.all
        render "mainpage"
    end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/views/admin/courses/_form.html.erb
<% if flash[:error] %>
<div class='error'><%= flash[:error] %></div>
<% end %>
<%= form_for [:admin, @course], html: { multipart: true } do |f| %>
<%= f.label :datum %>
<%= f.date_select :datum %><br/>
<%= f.label :name %>
<%= f.text_field :name %><br/>
<%= f.label :logo %>
<%= f.file_field :logo %><br/>
<%= link_to 'Mégsem', admin_path %>
<%= f.submit 'Mentés' %>
<% end %>

app/views/admin/courses/edit.html.erb
<%= render 'form' %>

app/views/admin/courses/new.html.erb
<%= render 'form' %>

app/views/admin/dashboard/index.html.erb
<h1>Tanfolyamjaink</h1>

<%= link_to 'Logout', destroy_teacher_session_path, method: :delete %>

<%= link_to 'New', new_admin_course_path %>

<%= link_to 'Teszt email', admin_tesztemail_path %>

<%= link_to 'Dátum növelése', admin_incrementdate_path %>

<%= link_to 'PDF', admin_pdf_path %>

<table border="1">
<% @courses.each do |l| %>
<tr>
<td><%= l.datum %></td>
<td><%= image_tag l.logo.url(:thumb) %></td>
<td><%= link_to l.name, admin_course_lessons_path(l.id) %></td>
<td><%= link_to "Edit", edit_admin_course_path(l) %> <%= link_to "Delete", admin_course_path(l), method: :delete, data: { confirm: "Biztos?", tanfolyam: 'ruby' } %> 


<%#= link_to "Lessons", admin_course_lessons_path(l) %></td>
</tr>
<% end %>
</table>

app/views/admin/lessons/_form.html.erb
<% if flash[:error] %>
<div class='error'><%= flash[:error] %></div>
<% end %>
<%= form_for [:admin, @lesson.course, @lesson] do |f| %>
<%= f.label :datum %>
<%= f.date_select :datum %><br/>
<%= f.label :allapot %>
<%= f.text_field :allapot %><br/>
<%= link_to 'Mégsem', admin_course_lessons_path(@lesson.course_id) %>
<%= f.submit 'Mentés' %>
<% end %>

app/views/admin/lessons/edit.html.erb
<%= render 'form' %>

app/views/admin/lessons/index.html.erb
<h1><%= @course.name %> lessons</h1>

<%= link_to "New", new_admin_course_lesson_path(@course.id) %>

<table border="1">
<% @lessons.each do |l| %>
<tr>
<td><%= l.datum %></td>
<td><%= l.allapot %></td>
<td><%= link_to "Edit", edit_admin_course_lesson_path(@course.id, l.id) %></td>
</tr>
<% end %>
</table>

app/views/admin/lessons/new.html.erb
<%= render 'form' %>

app/views/admin/users/_form.html.erb
<% if flash[:error] %>
<div class='error'><%= flash[:error] %></div>
<% end %>
<%= form_for [:admin, @user] do |f| %>
  <%= f.label :firtname %>
  <%= f.text_field :firstname %><br/>
  <%= f.label :lastname %>
  <%= f.text_field :lastname %><br/>
  <%= f.label :birthdate %>
  <%= f.date_select :birthdate %><br/>
  <%= link_to 'Mégsem', admin_users_path %>
  <%= f.submit 'Mentés' %>

  <br/><br/>
  <% @courses.includes(:lessons).each do |c| %>
  <%= c.name %>:<br/>
      <% c.lessons.each do |l| %>
      <%= check_box_tag "lesson[#{l.id}]", 1, @user.presences.map { |p| p.lesson_id }.include?(l.id) %><%= label_tag "lesson_#{l.id}", l.datum %><br/>
      <% end %>
  <% end %>

<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= link_to "New", new_admin_user_path %>

<table border="1">
<% @users.each do |u| %>
<tr>
<td><%= u.name %></td>
<td><%= u.birthdate %></td>
<td><%= link_to "Edit", edit_admin_user_path(u.id) %> <%= link_to "Delete", admin_user_path(u.id), method: :delete %></td>
</tr>
<% end %>
</table>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/frontend/index.html.erb
<% console %>

app/views/frontend/mainpage.html.haml
%table.table.table-striped
  %tr
    %td Dátum
    %td Neve
  - @courses.each do |course|
    %tr
      %td
        = course.datum
      %td
        = course.name
   
  